### ISSUE TITLE
Netlify CMS breaking when making updates to practices

### ISSUE THREAD

**Issue by sashperso** [openpracticelibrary/openpracticelibrary#2161]
Hi all, this morning I was attempting to update the `A/B testing` practice to use Ilaria Doria's doodle as the cover image and when I went to save the page I received this error:

```
TypeError: Cannot read properties of undefined (reading 'type') at o (/admin/cms.js:2:30755) at u (/admin/cms.js:2:32412) at fe.ownerState (/admin/cms.js:75:8737) at o (/admin/cms.js:2:838823) at P (/admin/cms.js:2:832929) at z (/admin/cms.js:2:833224) at /admin/cms.js:2:834524 at /admin/cms.js:2:11137 at of (/admin/react-dom.production.min.js:109:301) at ni (/admin/react-dom.production.min.js:123:490)
```
Screenshot for reference:
![image](https://github.com/openpracticelibrary/openpracticelibrary/assets/100399398/b8f38378-447f-4f06-b16c-51468d2b5308)

**Comment by kattekrab** [comment]
I just hit the same issue :(

**Comment by kattekrab** [comment]
fixed.
